---
name: local-test
on: # yamllint disable-line rule:truthy
  pull_request:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./
        with:
          config_file: .markdownlint.yaml
          files: .
          ignore_files: "examples/ignore/*"
          rules: examples/rules/custom.json
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
