---
name: local-test
on: # yamllint disable-line rule:truthy
  pull_request:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./
        with:
          config_file: .markdownlintrc
          files: .
          ignore_files: "examples/ignore/*"
          rules: examples/rules/custom.js
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
